spring:
  datasource:
    url:      jdbc:mysql://localhost:3306/slideshow
    username: root
    password:

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl:
          auto: update

    show-sql: true

slideshow:
  urlValidator:
    connectionTimeout: 1000
    readTimeout: 1000